name: Auto Update AynaOTT Playlist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unzip main.py with password
      env:
        ZIP_PASS: ${{ secrets.ZIP_PASSWORD }}
      run: |
        sudo apt-get install -y unzip
        unzip -P "$ZIP_PASS" main.py.zip

    - name: Execute Script
      run: python main.py

    - name: Secure Cleanup
      run: rm -f main.py

    - name: Commit and Push Generated Files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        if [ -f AynaOTT.m3u ] && [ -f AynaOTT.json ]; then
          git add AynaOTT.m3u AynaOTT.json
          git diff-index --quiet HEAD || git commit -m "Auto Updated Playlist: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push
        else
          echo "Error: Output files missing. Script failed to fetch data."
          exit 1
        fi
